spring.application.name=virality-engine
spring.datasource.url=jdbc:postgresql://localhost:5433/virality_db?options=-c%20timezone=UTC
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=localhost
spring.data.redis.port=6379
